spring:
  cloud:
    config:
      server:
        git:
          uri: C:/Testing Projects/microservicesrepo
  application:
    name: spring-cloud-config-server
server:
  port: 8888
  
management.endpoints.web.exposure.include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defalutZone: http://localhost:8761