spring:
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: spring-cloud-config-client
      
      
management.endpoints.web.exposure.include: refresh
        
message: Hello message from config server server 222

server.port: 8086

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defalutZone: http://localhost:8761